### ISSUE TITLE
Support the latest release of LCLS (Q4-2024)

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#342]
- [ ] Test with LCLS snapshot drivers when available: https://github.com/OpenLiberty/liberty-language-server

There are two dependencies that need to be updated:
- liberty-langserver-lemminx-2.1.1-jar-with-dependencies.jar
- liberty-langserver-2.1.1-jar-with-dependencies.jar

The below three files are affected:
- gulpfile.js
- package.json
- src/extension.ts

Check for any regression in LCLS behaviour.
Determine new LCLS behaviour to test and verify it behaves as expected (i.e. support for versionless features).

If any problems are discovered, open issues and track them in this issue.

- [ ] #348
- [ ] #349
- [ ] #350
- [ ] https://github.com/OpenLiberty/liberty-tools-vscode/issues/343 
- [ ] https://github.com/OpenLiberty/liberty-tools-vscode/issues/332
- [ ] https://github.com/OpenLiberty/liberty-tools-vscode/issues/357
- [ ] https://github.com/OpenLiberty/liberty-language-server/issues/317
