### ISSUE TITLE
VS Code workspace related changes.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-vscode#453]
- [ ] https://github.com/OpenLiberty/liberty-tools-vscode/issues/386
- [ ] https://github.com/OpenLiberty/liberty-tools-vscode/issues/396
- [ ] https://github.com/OpenLiberty/liberty-tools-vscode/issues/395
- [ ] https://github.com/OpenLiberty/liberty-tools-vscode/issues/394

**Comment by JoshwinThomasIBM** [comment]
We need answers for the below to proceed with the workspace related changes in this epic . These are raised in vs code discussions forum.

[How can we retrieve the workspace name after the save operation in the deactivate() method?](https://github.com/microsoft/vscode-discussions/discussions/2458)

[Can we hook into the workspace save workflow when the user tries to save the workspace?](https://github.com/microsoft/vscode-discussions/discussions/2457)

[Can VS Code determine if a session is active based on a provided session ID?](https://github.com/microsoft/vscode-discussions/discussions/2456)

[Is it possible to clear data stored in the global state directly from the deactivate() method of an extension?](https://github.com/microsoft/vscode-discussions/discussions/2455)
